---
title: "Anonymize Data"
author: "Will Schulz"
date: "2023-04-25"
output: html_document
---

```{r}
library(tidyverse)
library(rechat)
```


```{r}
dir.create("data")
dir.create("data/study_1")
dir.create("data/study_2")
```




```{r}
# Study 1 survey data
readRDS("../raw_data/study_1/raw_survey_data.rds") %>% select(-workerId, -assignmentId, -hitId, -feedback_freetext) %>% saveRDS(., "data/study_1/raw_survey_data.rds")

# Study 2 survey data
readRDS("../raw_data/study_2/raw_survey_data.rds") %>% select(-workerId, -assignmentId, -hitId, -feedback_freetext) %>% saveRDS(., "data/study_2/raw_survey_data.rds")
```




```{r}
# file = "../raw_data/study_1/47cb1084-4cf5-4697-be97-f6447c9f186a.csv"
# 
# chat_table <- read_lines(file)
# chat_data <- parseChat(file)
# 
# get_nicknames <- function(x){
#   return(x$participants$nickname)
# }
# 
# nicknames <- sapply(chat_data, get_nicknames) %>% unlist %>% unique
# #nicknames
# 
# lines_to_anonymize <- str_starts(chat_table, '\"#') & str_ends(chat_table, ',\"Human\"')
# chat_table[lines_to_anonymize] <- gsub(paste(paste0('\"', nicknames, '\"'), collapse = "|"), '\"ANONYMIZED\"', chat_table[lines_to_anonymize])
# #chat_table[1:10]
# 
# write_lines(chat_table, file = "data/study_1/47cb1084-4cf5-4697-be97-f6447c9f186a.csv")
# test <- parseChat("data/study_1/47cb1084-4cf5-4697-be97-f6447c9f186a.csv")
# #test[[5]]
```


# Anonymize Chat Data

```{r}
get_nicknames <- function(x){
  return(x$participants$nickname)
}

anonymizeChats <- function(file, out_path){
  chat_table <- read_lines(file)
  chat_data <- parseChat(file)
  nicknames <- sapply(chat_data, get_nicknames) %>% unlist %>% unique
  lines_to_anonymize <- str_starts(chat_table, '\"#') & str_ends(chat_table, ',\"Human\"')
  chat_table[lines_to_anonymize] <- gsub(paste(paste0('\"', nicknames, '\"'), collapse = "|"), '\"ANONYMIZED\"', chat_table[lines_to_anonymize])
  write_lines(chat_table, file = out_path)
}

```


```{r}
anonymizeChats("../raw_data/study_1/47cb1084-4cf5-4697-be97-f6447c9f186a.csv", "data/study_1/47cb1084-4cf5-4697-be97-f6447c9f186a.csv")
anonymizeChats("../raw_data/study_1/3583fe12-0f20-44b6-a08d-878ce3842b58.csv", "data/study_1/3583fe12-0f20-44b6-a08d-878ce3842b58.csv")
anonymizeChats("../raw_data/study_2/dem_chats_asof_220601.csv", "data/study_2/dem_chats_asof_220601.csv")
anonymizeChats("../raw_data/study_2/rep_chats_asof_220601.csv", "data/study_2/rep_chats_asof_220601.csv")
```

